server {
    listen 80;
    
    # Root directory onde estão os ficheiros compilados da App
    root /usr/share/nginx/html;
    index index.html;

    # Qualquer rota vai carregar o index.html (necessário para apps React/SPA)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Otimizações de Cache para ficheiros estáticos (js, css, imagens)
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public, max-age=15552000, immutable";
    }
}
